axis_linear:
  x: 0
  y: 1
  z: 3
scale_linear:
  x: -0.02
  y: 0.02
  z: 0.2
axis_angular:
  yaw: 2
scale_angular:
  yaw: 1
  
enable_button: 5  # R2 shoulder button
enable_turbo_button: -1  # R1 shoulder button
