<?xml version="1.0"?>

<robot name="morus" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="mesh_file" value="MORUS_UAV_without_mass.dae" />
  <xacro:property name="mesh_file_mass" value="MORUS_mass.dae" />
  <xacro:property name="mass" value="30" />  <!-- [kg] -->

  <xacro:property name="body_width" value="0.3" /> <!-- 0.1 [m] -->
  <xacro:property name="body_height" value="0.25" /> <!--0.2 [m] -->
  <xacro:property name="mass_rotor" value="0.2" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.515" /> <!-- [m] -->
  <xacro:property name="arm_offset" value="0.1" /> <!-- [m] -->
  <xacro:property name="propeler_offset" value="0.325" /> <!-- [m] -->
  
  <xacro:property name="rotor_offset_top" value="0.037" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.33" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="0.000456874" /> <!-- [kg*m/s^2] -->
  <xacro:property name="moment_constant" value="0.01" /> <!-- [m] -->
  <xacro:property name="time_constant" value="0.125" /> <!-- [s] -->s ti
  <xacro:property name="max_rot_velocity" value="838" /> <!-- [rad/s] -->

  <xacro:property name="rotor_drag_coefficient" value="8.06428e-04" />
  <xacro:property name="rolling_moment_coefficient" value="0.00001" />

  <!--wing properties -->
  <xacro:property name="wing_mass" value="0.001"/> <!-- [kg] -->
  <xacro:property name="wing_x" value="0.01"/> <!-- [m] -->
  <xacro:property name="wing_y" value="0.66"/> <!-- [m] -->
  <xacro:property name="wing_z" value="0.1"/> <!-- [m] -->
  <xacro:property name="arm_height" value="0.1" /> <!-- [m] added arm_height for no wing-rotor interaction -->
  <xacro:property name="area_control_flap" value="0.066"/> <!-- [m^2] -->
  <xacro:property name="area_antitorque_flap" value="0.066"/> <!-- [m^2] -->

  <!--realistic rotor properties -->
  <xacro:property name="fluid_density" value="1.2041" />  <!-- air -->
  <xacro:property name="distance_antitorque_flap" value="0.08" /> <!-- [m] distance from centre of gravity of rotor, force*distance=moment-->
  <xacro:property name="distance_control_flap" value="0.1" /> <!-- [m] -->
  <xacro:property name="thrust_coefficient" value="0.000456874" />  <!-- motor_constant Kf-->
  <xacro:property name="torque_coefficient" value="0.01" /> <!-- moment_constant Kt-->
  <xacro:property name="slip_velocity_coefficient" value="2.7e-02" /> <!-- Kv -->
  
  <xacro:property name="lift_coefficient_control_flap" value="8.5e-02" />  <!-- Clc -->
  <xacro:property name="drag_coefficient_control_flap" value="1.3e-01" />  <!-- Cdc -->
  <xacro:property name="lift_coefficient_antitorque_flap" value="3.4e-02" />  <!-- Cla -->
  <xacro:property name="drag_coefficient_antitorque_flap" value="1.3e-01" />  <!-- Cda -->

  <xacro:property name="lift_coefficient_control_flap_at0" value="0" />  <!-- Clc0 not used in the formulas -->
  <xacro:property name="drag_coefficient_control_flap_at0" value="7.47e-03" />  <!-- Cdc0 -->
  <xacro:property name="lift_coefficient_antitorque_flap_at0" value="1.358e-01" />  <!-- Cla0 -->
  <xacro:property name="drag_coefficient_antitorque_flap_at0" value="3.23e-03" />  <!-- Cda0 -->

  <xacro:property name="movable_mass_mass" value="1" />
  <xacro:property name="movable_mass_dimension" value="0.08" />
  <xacro:property name="movable_mass_offset" value="0.025" />

  <xacro:property name="imu_mass" value="0.02"/>
  <xacro:property name="imu_size" value="0.01"/>

  <xacro:property name="sin45" value="0.7071" />
  <xacro:property name="cos45" value="0.7071" />
  <xacro:property name="PI" value="3.14" />
  <xacro:property name="PIhalf" value="1.5707" />

  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
    <inertia ixx="5.5268" ixy="0.0" ixz="0.0" iyy="5.5268" iyz="0.0" izz="6.8854" />
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
  <xacro:property name="rotor_inertia">
    <inertia 
    ixx="${1/12 * mass_rotor * (0.015 * 0.015 + 0.003 * 0.003) * rotor_velocity_slowdown_sim}" 
    iyy="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.003 * 0.003) * rotor_velocity_slowdown_sim}" 
    izz="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.015 * 0.015) * rotor_velocity_slowdown_sim}" 
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <!-- inertia of a movable mass, assuming it is a cube. The formula is I=ms^2/6 where "s" is length of one side
   of the cube and "m" is its mass-->

  <xacro:property name="movable_mass_inertia">
     <inertia 
     ixx="${(movable_mass_mass * movable_mass_dimension * movable_mass_dimension)/6}" 
     iyy="${(movable_mass_mass * movable_mass_dimension * movable_mass_dimension)/6}" 
     izz="${(movable_mass_mass * movable_mass_dimension * movable_mass_dimension)/6}" 
     ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <xacro:property name="imu_inertia">
    <inertia 
    ixx="${(imu_mass * imu_size * imu_size)/6}" 
    iyy="${(imu_mass * imu_size * imu_size)/6}" 
    izz="${(imu_mass * imu_size * imu_size)/6}" 
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <!-- wing inertia -->
  <xacro:property name="wing_inertia">
    <inertia 
    ixx="${(wing_mass * wing_x * wing_x)/6}" 
    iyy="${(wing_mass * wing_y * wing_y)/6}" 
    izz="${(wing_mass * wing_z * wing_z)/6}" 
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find morus_description)/urdf/multirotor_base.urdf.xacro" />

  <!-- Instantiate multirotor_base_macro once-->
  <xacro:multirotor_base_macro
    robot_namespace="$(arg name)"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    mesh_file="${mesh_file}"
    mesh_file_mass="${mesh_file_mass}">
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Instantiate wing 0 -->
  <xacro:wing
    robot_namespace="$(arg name)" 
    parent="base_link"
    wing_number="0"
    mass="${wing_mass}"
    wing_x="${wing_x}"
    wing_y="${wing_y}"
    wing_z="${wing_z}"
    x_axis="0"
    y_axis="1"
    color="Red">
    <origin xyz="${arm_length+arm_offset} 0 ${-arm_height}" rpy="0 0 0" />
    <xacro:insert_block name="wing_inertia"/>
  </xacro:wing>

  <!-- Instantiate wing 1-->
  <xacro:wing
    robot_namespace="$(arg name)" 
    parent="base_link"
    wing_number="1"
    mass="${wing_mass}"
    wing_x="${wing_x}"
    wing_y="${wing_y}"
    wing_z="${wing_z}"
    x_axis="0"
    y_axis="1"
    color="Blue">
    <origin xyz="0 ${arm_length+arm_offset} ${-arm_height}" rpy="0 0 ${PIhalf}" />
    <xacro:insert_block name="wing_inertia"/>
  </xacro:wing>
  <!-- same x_axis and y_axis values as wing 0 because rpy flips the coordinate system by PIhalf-->

  <!-- Instantiate wing 2-->
  <xacro:wing
    robot_namespace="$(arg name)" 
    parent="base_link"
    wing_number="2"
    mass="${wing_mass}"
    wing_x="${wing_x}"
    wing_y="${wing_y}"
    wing_z="${wing_z}"
    x_axis="0"
    y_axis="1"
    color="Blue">
    <origin xyz="${-(arm_length+arm_offset)} 0 ${-arm_height}" rpy="0 0 0" />
    <xacro:insert_block name="wing_inertia"/>
  </xacro:wing>

  <!-- Instantiate wing 3-->
  <xacro:wing
    robot_namespace="$(arg name)" 
    parent="base_link"
    wing_number="3"
    mass="${wing_mass}"
    wing_x="${wing_x}"
    wing_y="${wing_y}"
    wing_z="${wing_z}"
    x_axis="0"
    y_axis="1"
    color="Blue">
    <origin xyz="0 ${-(arm_length+arm_offset)} ${-arm_height}" rpy="0 0 ${PIhalf}" />
    <xacro:insert_block name="wing_inertia"/>
  </xacro:wing>

  <!-- Instantiate tilt 0
  <xacro:tilt 
    motor_number="0" 
    parent="base_link"
    color="Red"
    x_axis="1"
    y_axis="0">
    <origin xyz="${arm_length+arm_offset} 0 0" rpy="0 0 0" />
  </xacro:tilt>-->

  <!-- Instantiate tilt 1 
  <xacro:tilt 
    motor_number="1" 
    parent="base_link"
    color="Blue"
    x_axis="0"
    y_axis="1">
    <origin xyz="0 ${arm_length+arm_offset} 0" rpy="0 0 0" />
  </xacro:tilt>-->


  <!-- Instantiate tilt 2 
  <xacro:tilt 
    motor_number="2" 
    parent="base_link"
    color="Blue"
    x_axis="-1"
    y_axis="0">
    <origin xyz="${-(arm_length+arm_offset)} 0 0" rpy="0 0 0" />
  </xacro:tilt>-->


  <!-- Instantiate tilt 3 
  <xacro:tilt 
    motor_number="3" 
    parent="base_link"
    color="Blue"
    x_axis="0"
    y_axis="-1">
    <origin xyz="0 ${-(arm_length+arm_offset)} 0" rpy="0 0 0" />
  </xacro:tilt>-->


  <xacro:transmisija
    trans_number="0"
    joint_name="wing_0_joint"> <!-- tilt_0_joint -->
  </xacro:transmisija>

  <xacro:transmisija
    trans_number="1"
    joint_name="wing_1_joint">
  </xacro:transmisija>

  <xacro:transmisija
    trans_number="2"
    joint_name="wing_2_joint">
  </xacro:transmisija>

  <xacro:transmisija
    trans_number="3"
    joint_name="wing_3_joint">
  </xacro:transmisija>


  <!-- Instantiate rotors -->   <!-- tilt_0-->
  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="front"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"

    area_control_flap="${area_control_flap}"
    area_antitorque_flap="${area_antitorque_flap}"
    fluid_density ="${fluid_density}"
    distance_control_flap="${distance_control_flap}"
    distance_antitorque_flap="${distance_antitorque_flap}"
    thrust_coefficient="${thrust_coefficient}"
    torque_coefficient="${torque_coefficient}"
    slip_velocity_coefficient="${slip_velocity_coefficient}"
    lift_coefficient_control_flap="${lift_coefficient_control_flap}"
    drag_coefficient_control_flap="${drag_coefficient_control_flap}"
    lift_coefficient_antitorque_flap="${lift_coefficient_antitorque_flap}"
    drag_coefficient_antitorque_flap="${drag_coefficient_antitorque_flap}"
    lift_coefficient_control_flap_at0="${lift_coefficient_control_flap_at0}"
    drag_coefficient_control_flap_at0="${drag_coefficient_control_flap_at0}"
    lift_coefficient_antitorque_flap_at0="${lift_coefficient_antitorque_flap_at0}"
    drag_coefficient_antitorque_flap_at0="${drag_coefficient_antitorque_flap_at0}"

    parent="base_link"   
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant="${time_constant}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"                
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red">
    <origin xyz="${arm_length+arm_offset} 0 ${propeler_offset}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    area_control_flap="${area_control_flap}"
    area_antitorque_flap="${area_antitorque_flap}"
    fluid_density ="${fluid_density}"
    distance_control_flap="${distance_control_flap}"
    distance_antitorque_flap="${distance_antitorque_flap}"
    thrust_coefficient="${thrust_coefficient}"
    torque_coefficient="${torque_coefficient}"
    slip_velocity_coefficient="${slip_velocity_coefficient}"
    lift_coefficient_control_flap="${lift_coefficient_control_flap}"
    drag_coefficient_control_flap="${drag_coefficient_control_flap}"
    lift_coefficient_antitorque_flap="${lift_coefficient_antitorque_flap}"
    drag_coefficient_antitorque_flap="${drag_coefficient_antitorque_flap}"
    lift_coefficient_control_flap_at0="${lift_coefficient_control_flap_at0}"
    drag_coefficient_control_flap_at0="${drag_coefficient_control_flap_at0}"
    lift_coefficient_antitorque_flap_at0="${lift_coefficient_antitorque_flap_at0}"
    drag_coefficient_antitorque_flap_at0="${drag_coefficient_antitorque_flap_at0}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant="${time_constant}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue">
    <origin xyz="0 ${arm_length+arm_offset} ${propeler_offset}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="back"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    area_control_flap="${area_control_flap}"
    area_antitorque_flap="${area_antitorque_flap}"
    fluid_density ="${fluid_density}"
    distance_control_flap="${distance_control_flap}"
    distance_antitorque_flap="${distance_antitorque_flap}"
    thrust_coefficient="${thrust_coefficient}"
    torque_coefficient="${torque_coefficient}"
    slip_velocity_coefficient="${slip_velocity_coefficient}"
    lift_coefficient_control_flap="${lift_coefficient_control_flap}"
    drag_coefficient_control_flap="${drag_coefficient_control_flap}"
    lift_coefficient_antitorque_flap="${lift_coefficient_antitorque_flap}"
    drag_coefficient_antitorque_flap="${drag_coefficient_antitorque_flap}"
    lift_coefficient_control_flap_at0="${lift_coefficient_control_flap_at0}"
    drag_coefficient_control_flap_at0="${drag_coefficient_control_flap_at0}"
    lift_coefficient_antitorque_flap_at0="${lift_coefficient_antitorque_flap_at0}"
    drag_coefficient_antitorque_flap_at0="${drag_coefficient_antitorque_flap_at0}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant="${time_constant}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue">
    <origin xyz="${-(arm_length+arm_offset)} 0 ${propeler_offset}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    area_control_flap="${area_control_flap}"
    area_antitorque_flap="${area_antitorque_flap}"
    fluid_density ="${fluid_density}"
    distance_control_flap="${distance_control_flap}"
    distance_antitorque_flap="${distance_antitorque_flap}"
    thrust_coefficient="${thrust_coefficient}"
    torque_coefficient="${torque_coefficient}"
    slip_velocity_coefficient="${slip_velocity_coefficient}"
    lift_coefficient_control_flap="${lift_coefficient_control_flap}"
    drag_coefficient_control_flap="${drag_coefficient_control_flap}"
    lift_coefficient_antitorque_flap="${lift_coefficient_antitorque_flap}"
    drag_coefficient_antitorque_flap="${drag_coefficient_antitorque_flap}"
    lift_coefficient_control_flap_at0="${lift_coefficient_control_flap_at0}"
    drag_coefficient_control_flap_at0="${drag_coefficient_control_flap_at0}"
    lift_coefficient_antitorque_flap_at0="${lift_coefficient_antitorque_flap_at0}"
    drag_coefficient_antitorque_flap_at0="${drag_coefficient_antitorque_flap_at0}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant="${time_constant}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue">
    <origin xyz="0 ${-(arm_length+arm_offset)} ${propeler_offset}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>


  <xacro:property name="land_gear_inertia">
    <inertia
    ixx="1e-6"
    iyy="1e-6"
    izz="1e-6"
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <xacro:landing_gear
      parent="base_link"
      gear_num = "1"
      mass = "1e-6"
      dim_x = "0.8"
      dim_y = "0.1"
      dim_z = "0.05">
      <origin xyz="0 -0.325 -0.6" rpy="0 0 0" />
      <xacro:insert_block name="land_gear_inertia"/>
  </xacro:landing_gear>

  <xacro:landing_gear
      parent="base_link"
      gear_num = "2"
      mass = "1e-6"
      dim_x = "0.8"
      dim_y = "0.1"
      dim_z = "0.05">
      <origin xyz="0 0.325 -0.6" rpy="0 0 0" />
      <xacro:insert_block name="land_gear_inertia"/>
  </xacro:landing_gear>


</robot>
