morus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Angle of Wing Controllers ---------------------------------
  angle_wing_0_controller:
    type: effort_controllers/JointPositionController
    joint: wing_0_joint
    pid: {p: 0.001, i: 0.0001, d: 0.01, i_clamp_max: 100.0, i_clamp_min: -100.0}
  angle_wing_1_controller:
    type: effort_controllers/JointPositionController
    joint: wing_1_joint
    pid: {p: 0.001, i: 0.0001, d: 0.01, i_clamp_max: 100.0, i_clamp_min: -100.0}
  angle_wing_2_controller:
    type: effort_controllers/JointPositionController
    joint: wing_2_joint
    pid: {p: 0.001, i: 0.0001, d: 0.01, i_clamp_max: 100.0, i_clamp_min: -100.0}
  angle_wing_3_controller:
    type: effort_controllers/JointPositionController
    joint: wing_3_joint
    pid: {p: 0.001, i: 0.0001, d: 0.01, i_clamp_max: 100.0, i_clamp_min: -100.0}
