Header header

float64 roll_sp
float64 roll_mv
float64 roll_rate_sp
float64 roll_rate_mv
float64 roll_comp
float64 roll_rate_comp
float64 roll_switch
float64 roll_rate_switch
float64 roll_ff
float64 roll_rate_ff
float64 roll_pid
float64 roll_rate_pid

float64 pitch_sp
float64 pitch_mv
float64 pitch_rate_sp
float64 pitch_rate_mv
float64 pitch_comp
float64 pitch_rate_comp
float64 pitch_switch
float64 pitch_rate_switch
float64 pitch_ff
float64 pitch_rate_ff
float64 pitch_pid
float64 pitch_rate_pid

float64 roll_offset
float64 pitch_offset
