Header header

float64 z_sp
float64 z_mv
float64 vz_sp
float64 vz_mv
float64 z_comp
float64 vz_comp
float64 z_switch
float64 vz_switch
float64 z_ff
float64 vz_ff
float64 z_pid
float64 vz_pid

float64 yaw_sp
float64 yaw_mv
float64 yaw_rate_sp
float64 yaw_rate_mv
float64 yaw_comp
float64 yaw_rate_comp
float64 yaw_switch
float64 yaw_rate_switch
float64 yaw_ff
float64 yaw_rate_ff
float64 yaw_pid
float64 yaw_rate_pid

float64 rotor_vel
float64 yaw_rotor_vel
